#!/bin/bash -e

npm install

export grep=$1

# Use bacon from bower instead of node.js
export NODE_PATH="$NODE_PATH:./components"

./node_modules/mocha/bin/mocha --compilers coffee:coffee-script test/**

if [ ! $grep ]; then
  node_modules/mocha-phantomjs/bin/mocha-phantomjs browsertest/runner.html
else
  echo "skipping browser tests"
fi
