#!/usr/bin/env node

// Custom browserify script to shim JQuery

var browserify = require('browserify')
  , shim = require('browserify-shim')
  , fs = require('fs')

shim(browserify(), {
  // jQuery attaches itself to the window as '$' so we assign the exports accordingly
  jquery: {
    path: './jquery.js',
    exports: '$'
  },
  bacon: {
    path: '../../components/bacon',
    exports: 'Bacon'
  }
}).
require(require.resolve('../../dist/Bacon.JQuery.Bindings.js'), { expose: 'bacon-jquery-bindings' })
.require(require.resolve('./example.js'), { entry: true })
.bundle(function (err, src) {
  if (err) return console.error(err);

  fs.writeFileSync("bundle.js", src);
});
